window.INDIAN_STATES = [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 
    'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 
    'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 
    'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 
    'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands', 'Chandigarh', 
    'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 
    'Lakshadweep', 'Puducherry'
];

window.CHINESE_PROVINCES = [
    'Anhui', 'Beijing', 'Chongqing', 'Fujian', 'Gansu', 'Guangdong', 'Guangxi', 'Guizhou', 
    'Hainan', 'Hebei', 'Heilongjiang', 'Henan', 'Hubei', 'Hunan', 'Inner Mongolia', 'Jiangsu', 
    'Jiangxi', 'Jilin', 'Liaoning', 'Ningxia', 'Qinghai', 'Shaanxi', 'Shandong', 'Shanghai', 
    'Shanxi', 'Sichuan', 'Tianjin', 'Tibet', 'Xinjiang', 'Yunnan', 'Zhejiang', 'Taiwan'
];

window.CHINA_NAME_MAPPING = {
    "安徽": "Anhui", "安徽省": "Anhui",
    "北京": "Beijing", "北京市": "Beijing",
    "重庆": "Chongqing", "重庆市": "Chongqing",
    "福建": "Fujian", "福建省": "Fujian",
    "甘肃": "Gansu", "甘肃省": "Gansu",
    "广东": "Guangdong", "广东省": "Guangdong",
    "广西": "Guangxi", "广西壮族自治区": "Guangxi",
    "贵州": "Guizhou", "贵州省": "Guizhou",
    "海南": "Hainan", "海南省": "Hainan",
    "河北": "Hebei", "河北省": "Hebei",
    "黑龙江": "Heilongjiang", "黑龙江省": "Heilongjiang",
    "河南": "Henan", "河南省": "Henan",
    "湖北": "Hubei", "湖北省": "Hubei",
    "湖南": "Hunan", "湖南省": "Hunan",
    "内蒙古": "Inner Mongolia", "内蒙古自治区": "Inner Mongolia",
    "江苏": "Jiangsu", "江苏省": "Jiangsu",
    "江西": "Jiangxi", "江西省": "Jiangxi",
    "吉林": "Jilin", "吉林省": "Jilin",
    "辽宁": "Liaoning", "辽宁省": "Liaoning",
    "宁夏": "Ningxia", "宁夏回族自治区": "Ningxia",
    "青海": "Qinghai", "青海省": "Qinghai",
    "陕西": "Shaanxi", "陕西省": "Shaanxi",
    "山东": "Shandong", "山东省": "Shandong",
    "上海": "Shanghai", "上海市": "Shanghai",
    "山西": "Shanxi", "山西省": "Shanxi",
    "四川": "Sichuan", "四川省": "Sichuan",
    "天津": "Tianjin", "天津市": "Tianjin",
    "西藏": "Tibet", "西藏自治区": "Tibet",
    "新疆": "Xinjiang", "新疆维吾尔自治区": "Xinjiang",
    "云南": "Yunnan", "云南省": "Yunnan",
    "浙江": "Zhejiang", "浙江省": "Zhejiang",
    "香港": "Hong Kong", "香港特别行政区": "Hong Kong",
    "澳门": "Macau", "澳门特别行政区": "Macau",
    "台湾": "Taiwan", "台湾省": "Taiwan"
};

window.JAPAN_PREFECTURES = [
    'Hokkaido', 'Aomori', 'Iwate', 'Miyagi', 'Akita', 'Yamagata', 'Fukushima',
    'Ibaraki', 'Tochigi', 'Gunma', 'Saitama', 'Chiba', 'Tokyo', 'Kanagawa',
    'Niigata', 'Toyama', 'Ishikawa', 'Fukui', 'Yamanashi', 'Nagano', 'Gifu',
    'Shizuoka', 'Aichi', 'Mie', 'Shiga', 'Kyoto', 'Osaka', 'Hyogo', 'Nara',
    'Wakayama', 'Tottori', 'Shimane', 'Okayama', 'Hiroshima', 'Yamaguchi',
    'Tokushima', 'Kagawa', 'Ehime', 'Kochi', 'Fukuoka', 'Saga', 'Nagasaki',
    'Kumamoto', 'Oita', 'Miyazaki', 'Kagoshima', 'Okinawa'
];

window.JAPAN_NAME_MAPPING = {
    "北海道": "Hokkaido",
    "青森": "Aomori", "青森県": "Aomori",
    "岩手": "Iwate", "岩手県": "Iwate",
    "宮城": "Miyagi", "宮城県": "Miyagi",
    "秋田": "Akita", "秋田県": "Akita",
    "山形": "Yamagata", "山形県": "Yamagata",
    "福島": "Fukushima", "福島県": "Fukushima",
    "茨城": "Ibaraki", "茨城県": "Ibaraki",
    "栃木": "Tochigi", "栃木県": "Tochigi",
    "群馬": "Gunma", "群馬県": "Gunma",
    "埼玉": "Saitama", "埼玉県": "Saitama",
    "千葉": "Chiba", "千葉県": "Chiba",
    "東京": "Tokyo", "東京都": "Tokyo",
    "神奈川": "Kanagawa", "神奈川県": "Kanagawa",
    "新潟": "Niigata", "新潟県": "Niigata",
    "富山": "Toyama", "富山県": "Toyama",
    "石川": "Ishikawa", "石川県": "Ishikawa",
    "福井": "Fukui", "福井県": "Fukui",
    "山梨": "Yamanashi", "山梨県": "Yamanashi",
    "長野": "Nagano", "長野県": "Nagano",
    "岐阜": "Gifu", "岐阜県": "Gifu",
    "静岡": "Shizuoka", "静岡県": "Shizuoka",
    "愛知": "Aichi", "愛知県": "Aichi",
    "三重": "Mie", "三重県": "Mie",
    "滋賀": "Shiga", "滋賀県": "Shiga",
    "京都": "Kyoto", "京都府": "Kyoto",
    "大阪": "Osaka", "大阪府": "Osaka",
    "兵庫": "Hyogo", "兵庫県": "Hyogo",
    "奈良": "Nara", "奈良県": "Nara",
    "和歌山": "Wakayama", "和歌山県": "Wakayama",
    "鳥取": "Tottori", "鳥取県": "Tottori",
    "島根": "Shimane", "島根県": "Shimane",
    "岡山": "Okayama", "岡山県": "Okayama",
    "広島": "Hiroshima", "広島県": "Hiroshima",
    "山口": "Yamaguchi", "山口県": "Yamaguchi",
    "徳島": "Tokushima", "徳島県": "Tokushima",
    "香川": "Kagawa", "香川県": "Kagawa",
    "愛媛": "Ehime", "愛媛県": "Ehime",
    "高知": "Kochi", "高知県": "Kochi",
    "福岡": "Fukuoka", "福岡県": "Fukuoka",
    "佐賀": "Saga", "佐賀県": "Saga",
    "長崎": "Nagasaki", "長崎県": "Nagasaki",
    "熊本": "Kumamoto", "熊本県": "Kumamoto",
    "大分": "Oita", "大分県": "Oita",
    "宮崎": "Miyazaki", "宮崎県": "Miyazaki",
    "鹿児島": "Kagoshima", "鹿児島県": "Kagoshima",
    "沖縄": "Okinawa", "沖縄県": "Okinawa"
};

window.BRAZIL_STATES = [
    'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará', 'Distrito Federal', 
    'Espírito Santo', 'Goiás', 'Maranhão', 'Mato Grosso', 'Mato Grosso do Sul', 
    'Minas Gerais', 'Pará', 'Paraíba', 'Paraná', 'Pernambuco', 'Piauí', 'Rio de Janeiro', 
    'Rio Grande do Norte', 'Rio Grande do Sul', 'Rondônia', 'Roraima', 'Santa Catarina', 
    'São Paulo', 'Sergipe', 'Tocantins'
];